/* InSync representative cookbook pilot.
   These 48 records are intentionally separate from the generated foundation
   catalog. They are structurally validated development content, not culinary
   or nutrition-approved recipes. Nutrition is calculated from generic food
   reference values and every mapping still requires a specific source ID. */
(function () {
  'use strict';

  var SOURCE_URL='https://fdc.nal.usda.gov/';
  var NUTRIENTS=window.InSyncNutrientRegistry||null;
  var FOOD={
    oats:['Rolled oats',379,13.2,67.7,6.5,10.1,6,[],true,true],
    milk:['Low-fat milk',42,3.4,5,1,0,44,['milk'],false,true],
    yogurt:['Plain Greek yogurt',59,10.3,3.6,0.4,0,36,['milk'],false,true],
    cottage:['Low-fat cottage cheese',82,11.1,3.4,2.3,0,364,['milk'],false,true],
    egg:['Large egg',143,12.6,0.7,9.5,0,142,['egg'],false,true],
    whites:['Egg whites',52,10.9,0.7,0.2,0,166,['egg'],false,true],
    chicken:['Chicken breast',165,31,0,3.6,0,74,[],false,true],
    turkey:['Lean ground turkey',170,29,0,7,0,70,[],false,true],
    salmon:['Salmon',206,22,0,12,0,59,['fish'],false,true],
    tuna:['Canned tuna in water, drained',116,25.5,0,0.8,0,247,['fish'],false,true],
    tofu:['Firm tofu',144,17.3,2.8,8.7,2.3,14,['soy'],true,true],
    paneer:['Paneer',296,20,3.6,22,0,22,['milk'],false,true],
    chickpeas:['Cooked chickpeas',164,8.9,27.4,2.6,7.6,7,[],true,true],
    lentils:['Cooked lentils',116,9,20.1,0.4,7.9,2,[],true,true],
    blackBeans:['Cooked black beans',132,8.9,23.7,0.5,8.7,2,[],true,true],
    edamame:['Shelled edamame',121,11.9,8.9,5.2,5.2,6,['soy'],true,true],
    rice:['Cooked brown rice',123,2.7,25.6,1.6,1.6,4,[],true,true],
    whiteRice:['Cooked white rice',130,2.7,28.2,0.3,0.4,1,[],true,true],
    wildRice:['Cooked wild rice',101,4,21.3,0.3,1.8,3,[],true,true],
    quinoa:['Cooked quinoa',120,4.4,21.3,1.9,2.8,7,[],true,true],
    couscous:['Cooked whole-wheat couscous',112,3.8,23.2,0.2,1.4,5,['wheat'],true,false],
    soba:['Cooked buckwheat soba noodles',99,5.1,21.4,0.1,0,60,['wheat'],true,false],
    bread:['Whole-grain bread',247,12.5,41.4,3.4,6.8,430,['wheat'],true,false],
    flour:['Whole-wheat flour',340,13.2,72,2.5,10.7,2,['wheat'],true,false],
    besan:['Chickpea flour',387,22.4,57.8,6.7,10.8,64,[],true,true],
    potato:['Cooked potato',87,1.9,20.1,0.1,1.8,4,[],true,true],
    sweetPotato:['Cooked sweet potato',90,2,20.7,0.2,3.3,36,[],true,true],
    blueberry:['Blueberries',57,0.7,14.5,0.3,2.4,1,[],true,true],
    apple:['Apple',52,0.3,13.8,0.2,2.4,1,[],true,true],
    banana:['Banana',89,1.1,22.8,0.3,2.6,1,[],true,true],
    mango:['Mango',60,0.8,15,0.4,1.6,1,[],true,true],
    fig:['Dried figs',249,3.3,63.9,0.9,9.8,10,[],true,true],
    berries:['Mixed berries',50,0.8,12,0.3,4,1,[],true,true],
    avocado:['Avocado',160,2,8.5,14.7,6.7,7,[],true,true],
    tomato:['Tomato',18,0.9,3.9,0.2,1.2,5,[],true,true],
    onion:['Onion',40,1.1,9.3,0.1,1.7,4,[],true,true],
    pepper:['Bell pepper',31,1,6,0.3,2.1,4,[],true,true],
    spinach:['Spinach',23,2.9,3.6,0.4,2.2,79,[],true,true],
    cucumber:['Cucumber',15,0.7,3.6,0.1,0.5,2,[],true,true],
    carrot:['Carrot',41,0.9,9.6,0.2,2.8,69,[],true,true],
    celery:['Celery',14,0.7,3,0.2,1.6,80,[],true,true],
    broccoli:['Broccoli',35,2.4,7.2,0.4,3.3,41,[],true,true],
    corn:['Corn kernels',96,3.4,21,1.5,2.4,1,[],true,true],
    peas:['Green peas',81,5.4,14.5,0.4,5.7,5,[],true,true],
    cabbage:['Cabbage',25,1.3,5.8,0.1,2.5,18,[],true,true],
    mushroom:['Mushrooms',22,3.1,3.3,0.3,1,5,[],true,true],
    zucchini:['Zucchini',17,1.2,3.1,0.3,1,8,[],true,true],
    greenBeans:['Green beans',31,1.8,7,0.1,2.7,6,[],true,true],
    seaweed:['Wakame seaweed, rehydrated',45,3,9,0.6,0.5,872,[],true,true],
    olive:['Olives',116,0.8,6,10.9,1.6,735,[],true,true],
    almonds:['Almonds',579,21.2,21.6,49.9,12.5,1,['tree nuts'],true,true],
    walnuts:['Walnuts',654,15.2,13.7,65.2,6.7,2,['tree nuts'],true,true],
    peanutButter:['Peanut butter',588,25,20,50,6,17,['peanut'],true,true],
    tahini:['Tahini',595,17,21,53.8,9.3,115,['sesame'],true,true],
    sesame:['Sesame seeds',573,17.7,23.4,49.7,11.8,11,['sesame'],true,true],
    feta:['Feta cheese',264,14.2,4.1,21.3,0,917,['milk'],false,true],
    oil:['Olive oil',884,0,0,100,0,0,[],true,true],
    coconutMilk:['Light coconut milk',72,0.7,2.7,7,0,15,[],true,true],
    miso:['Miso paste',199,12.8,26.5,6,5.4,3728,['soy'],true,true],
    soySauce:['Reduced-sodium tamari',60,10.5,5.6,0.1,0.8,3300,['soy'],true,true],
    honey:['Honey',304,0.3,82.4,0,0.2,4,[],false,true],
    spices:['Herbs and spices',250,10,45,8,25,50,[],true,true],
    lemon:['Lemon juice',22,0.4,6.9,0.2,0.3,1,[],true,true],
    lime:['Lime juice',25,0.4,8.4,0.1,0.4,2,[],true,true]
  };

  function round(v){return Math.round(v*10)/10;}
  function slug(v){return String(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function ing(spec){
    var id=spec[0],f=FOOD[id];
    if(!f)throw new Error('Unknown pilot ingredient: '+id);
    return {id:id,name:spec[6]||f[0],collection:'pilot',grams:spec[1],standard:{amount:spec[2],unit:spec[3]},section:spec[4]||'Main',optional:!!spec[5],allergens:f[7].slice(),sourceRef:'UNRESOLVED-'+id,preparationState:spec[7]||'as listed',scalable:true,rounding:'kitchen-practical'};
  }
  function nutrition(items,servings){
    if(NUTRIENTS&&typeof NUTRIENTS.calculate==='function')return NUTRIENTS.calculate(items,servings);
    var n={kcal:0,protein:0,carbs:0,fat:0,fiber:0,sodium:0};
    items.forEach(function(it){var f=FOOD[it.id],x=it.grams/100;n.kcal+=f[1]*x;n.protein+=f[2]*x;n.carbs+=f[3]*x;n.fat+=f[4]*x;n.fiber+=f[5]*x;n.sodium+=f[6]*x;});
    servings=Math.max(1,servings||1);Object.keys(n).forEach(function(k){n[k]=round(n[k]/servings);});return {nutrition:n,provenance:{calculationMethod:'Legacy embedded reference fallback',estimated:true,complete:false,sourceRecords:[],unresolvedMappings:items.map(function(it){return {ingredient:it.name,ingredientId:it.id,sourceRef:it.sourceRef,reason:'USDA registry was not loaded.'};})}};
  }
  function make(cuisine,slot,spec){
    var items=spec.i.map(ing), animal=items.some(function(x){return !FOOD[x.id][8];});
    var dairy=items.some(function(x){return x.allergens.indexOf('milk')>=0;});
    var gluten=items.some(function(x){return x.allergens.indexOf('wheat')>=0;});
    var fish=items.some(function(x){return x.allergens.indexOf('fish')>=0;});
    var allergens=[];items.forEach(function(x){x.allergens.forEach(function(a){if(allergens.indexOf(a)<0)allergens.push(a);});});
    var nutrientResult=nutrition(items,2);
    return {
      id:'rcp-pilot-'+slug(cuisine)+'-'+slug(slot)+'-'+slug(spec.n),version:1,name:spec.n,summary:spec.s,
      cuisine:cuisine,region:spec.r,regionalContext:spec.r,mealSlots:[slot],course:slot,proteins:spec.p,baseServings:2,yieldLabel:'2 adult servings',servingSize:{description:spec.y,gramsEstimate:Math.round(items.reduce(function(a,x){return a+x.grams;},0)/2),portionOptions:[0.75,1,1.25]},
      nutrition:nutrientResult.nutrition,nutritionBasis:'estimated per adult serving; mapped USDA ingredients only when unresolvedMappings is not empty',nutritionProvenance:nutrientResult.provenance,ingredients:items,instructions:spec.m,
      time:{prepMinutes:spec.t[0],cookMinutes:spec.t[1],totalMinutes:spec.t[0]+spec.t[1]},difficulty:spec.d||'Easy',equipment:spec.e,
      dietary:{vegetarian:!animal||(!fish&&items.every(function(x){return ['chicken','turkey','salmon','tuna'].indexOf(x.id)<0;})),vegan:!animal,glutenFree:!gluten,dairyFree:!dairy,pescatarian:!items.some(function(x){return ['chicken','turkey'].indexOf(x.id)>=0;}),porkFree:true},
      dietaryNotes:'Compatibility is ingredient-based and assumes certified products where required. Cross-contact is not assessed.',allergens:allergens,allergenCrossContact:'Check every packaged ingredient label and shared preparation surface.',
      tags:[slug(cuisine),slot.toLowerCase(),'pilot','whole-food'],flavor:spec.f,texture:spec.x,
      mealPrep:{suitable:spec.mp[0],refrigeratorDays:spec.mp[1],freezerDays:spec.mp[2],leftoverQuality:spec.mp[3],batchMaxServings:12,storageContainer:spec.mp[4],reheat:spec.mp[5]},storage:{refrigeratorDays:spec.mp[1],freezerDays:spec.mp[2],container:spec.mp[4],reheating:spec.mp[5]},
      foodSafety:{minimumInternalTemperatureC:spec.safe||null,notes:spec.fs},cost:{tier:spec.c||'moderate',estimated:true,currencyBasis:'profile-selected currency and user locale'},
      scaling:{minimumServings:1,maximumServings:20,method:'linear-by-canonical-quantity',baseServings:2,wholeItemRule:'Round eggs and other indivisible items up, then adjust leftovers.',seasoningNote:'Above four servings, begin with 75% of the scaled seasoning and adjust to taste.',liquidNote:'Hold back 10% of liquid when scaling above six servings; add as needed.'},
      substitutions:spec.sub,image:{asset:'',status:'needed',alt:spec.n+' served as described'},localization:{measurementModes:['standard','weight'],defaultLanguage:'en',translatable:true,ingredientAvailabilityNotes:spec.av||'Use locally available equivalent ingredients.'},
      provenance:{status:'draft-calculated',source:'Generic USDA FoodData Central reference values and InSync development recipe specification',sourceLinks:[SOURCE_URL],authorId:'insync-pilot-development',reviewHistory:[],reviewedBy:'',reviewedAt:'',notes:'Schema-tested only. Requires named culinary reviewer, specific nutrient source IDs, preparation testing, and nutrition reconciliation before production approval.'},
      review:{schema:'automated-pass',culinary:'pending',nutrition:'pending',allergen:'pending',culturalFit:'pending',production:'blocked'}
    };
  }

  function I(id,g,a,u,section,optional,name,prep){return [id,g,a,u,section,optional,name,prep];}
  var DATA={
    American:{
      Breakfast:[
        {n:'Blueberry Almond Overnight Oats',s:'Chilled oats with berries, yogurt, and toasted almonds.',r:'Contemporary American meal prep',p:['Greek yogurt','Almonds'],y:'1 filled breakfast jar',i:[I('oats',90,1,'cup','Base'),I('milk',180,0.75,'cup','Base'),I('yogurt',120,0.5,'cup','Protein'),I('blueberry',140,1,'cup','Fruit'),I('almonds',28,0.25,'cup','Finish'),I('spices',2,0.5,'teaspoon','Seasoning')],m:['Divide oats, milk, yogurt, and cinnamon between two jars and stir well.','Cover and refrigerate for at least 6 hours, until the oats are tender.','Top with blueberries and almonds immediately before serving.'],t:[10,0],e:['2 lidded jars','measuring cups','spoon'],f:['creamy','berry','cinnamon'],x:['soft','crunchy'],mp:[true,4,0,'excellent','sealed jar','Serve cold.'],fs:'Refrigerate within 2 hours and keep at 4 C / 40 F or colder.',sub:['Use sunflower seeds for almonds to remove tree nuts.','Use fortified soy yogurt and soy milk for a dairy-free version.']},
        {n:'Denver Egg and Potato Scramble',s:'A skillet scramble with eggs, potato, peppers, and onion.',r:'Mountain West diner-inspired',p:['Egg'],y:'1 heaped breakfast bowl',i:[I('egg',200,4,'large egg','Protein'),I('potato',220,1.5,'cups','Base'),I('pepper',100,0.75,'cup','Produce'),I('onion',60,0.5,'cup','Produce'),I('spinach',50,2,'cups','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('spices',3,1,'teaspoon','Seasoning')],m:['Heat the oil in a large skillet and brown the cooked potato for 5 minutes.','Add pepper and onion; cook until tender, then wilt in the spinach.','Beat the eggs with the seasoning, pour into the skillet, and stir gently until fully set.'],t:[12,15],e:['large skillet','mixing bowl','whisk','spatula'],f:['savory','peppery'],x:['tender','crisp-edged'],mp:[true,3,0,'good','airtight container','Reheat gently until steaming throughout.'],safe:71,fs:'Cook eggs until fully set; refrigerate leftovers promptly.',sub:['Use 300 g crumbled tofu for an egg-free scramble.','Use sweet potato in place of white potato.']},
        {n:'Apple Cinnamon Cottage Pancakes',s:'Protein-forward whole-grain pancakes with apple and cottage cheese.',r:'Contemporary American',p:['Cottage cheese','Egg'],y:'3 small pancakes',i:[I('cottage',200,0.875,'cup','Batter'),I('egg',100,2,'large egg','Batter'),I('flour',90,0.75,'cup','Batter'),I('apple',160,1,'medium apple','Fruit',false,null,'grated'),I('milk',60,0.25,'cup','Batter'),I('oil',5,1,'teaspoon','Pantry'),I('spices',3,1,'teaspoon','Seasoning')],m:['Blend cottage cheese, eggs, milk, and cinnamon until mostly smooth.','Fold in flour and grated apple; rest the batter for 5 minutes.','Cook six small pancakes on a lightly oiled skillet until browned and cooked through, flipping once.'],t:[12,12],e:['blender','mixing bowl','nonstick skillet','spatula'],f:['apple','cinnamon','mildly sweet'],x:['tender','soft'],mp:[true,3,30,'good','sealed container','Reheat in a skillet or toaster oven.'],fs:'Cook batter until the centers are set and refrigerate within 2 hours.',sub:['Use certified gluten-free oat flour for wheat flour.','Use pear in place of apple.']}
      ],
      Lunch:[
        {n:'Turkey Avocado Club Salad',s:'A bread-free club-style salad with turkey, avocado, and crunchy vegetables.',r:'American deli-inspired',p:['Turkey'],y:'1 large entree salad',i:[I('turkey',240,8.5,'ounces','Protein',false,null,'cooked and sliced'),I('avocado',120,0.8,'medium avocado','Produce'),I('tomato',180,1,'cup','Produce'),I('cucumber',150,1.5,'cups','Produce'),I('spinach',120,5,'cups','Greens'),I('lemon',30,2,'tablespoons','Dressing'),I('oil',18,4,'teaspoons','Dressing'),I('spices',3,1,'teaspoon','Seasoning')],m:['Whisk lemon juice, oil, and seasoning in a large bowl.','Add spinach, tomato, cucumber, and avocado and toss gently.','Divide between plates and arrange the cooked turkey over the top.'],t:[15,0],e:['large bowl','knife','cutting board','whisk'],f:['fresh','savory','bright'],x:['crisp','creamy'],mp:[false,1,0,'best fresh','separate dressing container','Serve cold; do not reheat.'],safe:74,fs:'Use fully cooked turkey; keep chilled ingredients at 4 C / 40 F or colder.',sub:['Use cooked chicken for turkey.','Use chickpeas for a plant-based version.']},
        {n:'Chicken and Wild Rice Soup',s:'A vegetable-rich chicken soup with wild rice.',r:'Upper Midwest-inspired',p:['Chicken'],y:'about 2 cups soup',i:[I('chicken',240,8.5,'ounces','Protein',false,null,'cooked and shredded'),I('wildRice',240,1.5,'cups','Grain'),I('carrot',120,1,'cup','Produce'),I('celery',100,1,'cup','Produce'),I('onion',100,0.75,'cup','Produce'),I('spinach',60,2.5,'cups','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('spices',4,1.5,'teaspoons','Seasoning')],m:['Heat oil in a soup pot; cook onion, carrot, and celery until softened.','Add 750 mL water, seasoning, chicken, and cooked wild rice; simmer for 12 minutes.','Stir in spinach, simmer until wilted, and serve piping hot.'],t:[15,25],e:['soup pot','knife','cutting board','ladle'],f:['herbal','savory'],x:['brothy','tender'],mp:[true,4,60,'excellent','shallow airtight container','Reheat to a rolling simmer.'],safe:74,fs:'Use fully cooked chicken and cool soup rapidly in shallow containers.',sub:['Use turkey for chicken.','Use cooked brown rice for wild rice.']},
        {n:'Black Bean Sweet Potato Grain Bowl',s:'A fiber-rich bowl with black beans, roasted sweet potato, and brown rice.',r:'Southwestern American-inspired',p:['Black beans'],y:'1 composed grain bowl',i:[I('blackBeans',260,1.5,'cups','Protein'),I('sweetPotato',300,2,'cups','Produce',false,null,'cubed'),I('rice',240,1.5,'cups','Grain'),I('corn',120,1,'cup','Produce'),I('avocado',100,0.67,'medium avocado','Finish'),I('lime',30,2,'tablespoons','Dressing'),I('oil',9,2,'teaspoons','Pantry'),I('spices',4,1.5,'teaspoons','Seasoning')],m:['Toss sweet potato with oil and seasoning; roast at 220 C / 425 F until browned and tender.','Warm black beans, corn, and cooked rice separately.','Divide rice into bowls, add the vegetables and beans, then finish with avocado and lime.'],t:[15,25],e:['sheet pan','saucepan','knife','2 bowls'],f:['smoky','earthy','bright'],x:['creamy','roasted'],mp:[true,4,30,'excellent','divided airtight container','Reheat rice, beans, and potato; add avocado after heating.'],fs:'Cool cooked components within 2 hours and store avocado separately.',sub:['Use quinoa for brown rice.','Use pinto beans for black beans.']}
      ],
      Dinner:[
        {n:'Herb-Roasted Chicken and Vegetables',s:'Sheet-pan chicken with potatoes, broccoli, and carrots.',r:'American home cooking',p:['Chicken'],y:'1 chicken and vegetable plate',i:[I('chicken',330,11.6,'ounces','Protein',false,null,'raw'),I('potato',320,2,'cups','Produce',false,null,'cubed'),I('broccoli',240,2.5,'cups','Produce'),I('carrot',180,1.5,'cups','Produce'),I('oil',18,4,'teaspoons','Pantry'),I('lemon',30,2,'tablespoons','Finish'),I('spices',5,2,'teaspoons','Seasoning')],m:['Heat oven to 220 C / 425 F and line a sheet pan.','Toss vegetables with half the oil and seasoning; add chicken coated with the remainder.','Roast until vegetables are tender and chicken reaches 74 C / 165 F, then finish with lemon.'],t:[15,30],e:['sheet pan','instant-read thermometer','knife','mixing bowl'],f:['herbal','lemony','savory'],x:['roasted','juicy'],mp:[true,4,60,'excellent','shallow airtight container','Reheat to 74 C / 165 F.'],safe:74,fs:'Keep raw chicken separate from produce and verify the thickest piece reaches 74 C / 165 F.',sub:['Use turkey tenderloin for chicken.','Use green beans for broccoli.']},
        {n:'Turkey Meatloaf with Sweet Potato Mash',s:'Individual turkey loaves with mashed sweet potato and peas.',r:'American comfort food',p:['Turkey'],y:'1 mini loaf with sides',i:[I('turkey',340,12,'ounces','Protein',false,null,'raw'),I('egg',50,1,'large egg','Binder'),I('oats',40,0.5,'cup','Binder',false,null,'finely ground'),I('onion',80,0.5,'cup','Produce'),I('tomato',120,0.67,'cup','Sauce'),I('sweetPotato',360,2.5,'cups','Side'),I('peas',180,1.5,'cups','Side'),I('spices',5,2,'teaspoons','Seasoning')],m:['Heat oven to 190 C / 375 F; combine turkey, egg, ground oats, onion, half the tomato, and seasoning.','Shape into two mini loaves, top with remaining tomato, and bake until the centers reach 74 C / 165 F.','Mash the hot sweet potato and serve with warmed peas and the meatloaves.'],t:[20,35],e:['sheet pan','mixing bowl','instant-read thermometer','potato masher'],f:['savory','tomato','comforting'],x:['tender','creamy'],mp:[true,4,60,'excellent','shallow airtight container','Reheat to 74 C / 165 F.'],safe:74,fs:'Wash hands after handling raw turkey and verify the center temperature.',sub:['Use lean ground chicken for turkey.','Use certified gluten-free oats when required.']},
        {n:'Maple Salmon Succotash',s:'Roasted salmon over corn, edamame, pepper, and tomato succotash.',r:'New England-inspired',p:['Salmon','Edamame'],y:'1 salmon fillet with succotash',i:[I('salmon',300,10.6,'ounces','Protein',false,null,'raw'),I('corn',200,1.67,'cups','Produce'),I('edamame',160,1.25,'cups','Protein'),I('pepper',140,1,'cup','Produce'),I('tomato',160,0.875,'cup','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('honey',14,2,'teaspoons','Glaze'),I('lemon',20,1.5,'tablespoons','Finish'),I('spices',4,1.5,'teaspoons','Seasoning')],m:['Heat oven to 205 C / 400 F; brush salmon with honey, lemon, and half the seasoning.','Roast until the salmon flakes and reaches the preferred safe doneness.','Saute corn, edamame, pepper, and tomato in oil; season and divide under the salmon.'],t:[15,18],e:['sheet pan','large skillet','instant-read thermometer','spatula'],f:['sweet-savory','lemony'],x:['flaky','crisp-tender'],mp:[true,3,30,'good','airtight container','Reheat gently to avoid drying the fish.'],safe:63,fs:'FDA consumer guidance uses 63 C / 145 F for fish; refrigerate promptly.',sub:['Use trout for salmon.','Use green peas for edamame to remove soy.'],c:'premium'}
      ],
      Snack:[
        {n:'Yogurt Berry Crunch Cups',s:'Greek yogurt layered with berries, oats, and almonds.',r:'Contemporary American',p:['Greek yogurt','Almonds'],y:'1 snack cup',i:[I('yogurt',300,1.25,'cups','Protein'),I('berries',180,1.25,'cups','Fruit'),I('oats',40,0.5,'cup','Crunch'),I('almonds',24,3,'tablespoons','Crunch'),I('spices',2,0.5,'teaspoon','Seasoning')],m:['Toast the oats and almonds in a dry skillet until fragrant, then cool.','Divide yogurt and berries between two cups.','Add the crunchy topping just before serving.'],t:[8,5],e:['small skillet','2 cups','spoon'],f:['tangy','berry'],x:['creamy','crunchy'],mp:[true,3,0,'excellent','separate topping cup','Serve cold.'],fs:'Keep yogurt refrigerated at 4 C / 40 F or colder.',sub:['Use pumpkin seeds for almonds.','Use dairy-free cultured soy yogurt for Greek yogurt.']},
        {n:'Apple Peanut Butter Celery Boats',s:'Crisp celery and apple filled with peanut butter.',r:'American lunchbox classic',p:['Peanut butter'],y:'3 filled celery pieces plus apple',i:[I('celery',180,6,'stalks','Produce'),I('apple',180,1,'medium apple','Produce',false,null,'sliced'),I('peanutButter',48,3,'tablespoons','Protein'),I('oats',20,0.25,'cup','Topping'),I('spices',1,0.25,'teaspoon','Seasoning')],m:['Wash and cut celery into six short boats.','Spread peanut butter into the celery and sprinkle with oats and cinnamon.','Divide with the sliced apple and serve immediately.'],t:[10,0],e:['knife','cutting board','spoon'],f:['nutty','apple','cinnamon'],x:['crisp','creamy'],mp:[false,1,0,'best fresh','airtight snack box','Do not reheat.'],fs:'Refrigerate cut produce and check peanut-allergy needs before serving.',sub:['Use sunflower seed butter for peanut butter.','Use pear for apple.']},
        {n:'Smoky Roasted Chickpeas',s:'Oven-roasted chickpeas seasoned with smoked spices.',r:'Contemporary American',p:['Chickpeas'],y:'about 3/4 cup',i:[I('chickpeas',300,1.75,'cups','Protein',false,null,'rinsed and dried'),I('oil',9,2,'teaspoons','Pantry'),I('spices',5,2,'teaspoons','Seasoning'),I('lime',15,1,'tablespoon','Finish'),I('carrot',160,1.25,'cups','Produce',true,null,'cut into sticks')],m:['Heat oven to 205 C / 400 F and dry the chickpeas thoroughly.','Toss chickpeas with oil and spices; roast until crisp, shaking the pan twice.','Cool for 10 minutes and serve with lime and optional carrot sticks.'],t:[8,32],e:['sheet pan','clean towel','mixing bowl'],f:['smoky','savory','bright'],x:['crisp'],mp:[true,2,0,'good','loosely covered container','Refresh for 5 minutes in a hot oven.'],fs:'Dry chickpeas before roasting to reduce splatter; cool before storing.',sub:['Use cooked white beans, noting they may be less crisp.','Use lemon for lime.']}
      ]
    }
  };

  /* The remaining cuisine packs are concise data additions to the same fully
     expanded contract. */
  function addPack(cuisine,pack){DATA[cuisine]=pack;}

  addPack('Indian',{
    Breakfast:[
      {n:'Vegetable Masala Oats',s:'Savory oats with peas, tomato, spinach, and warming spices.',r:'Indian home-style breakfast',p:['Oats','Peas'],y:'1 bowl',i:[I('oats',100,1.1,'cups','Base'),I('peas',140,1.2,'cups','Produce'),I('tomato',160,0.9,'cup','Produce'),I('spinach',80,3.3,'cups','Produce'),I('onion',80,0.5,'cup','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('spices',5,2,'teaspoons','Seasoning')],m:['Heat oil and cook onion with the spices until fragrant.','Add tomato and peas; cook until the tomato softens.','Stir in oats and 500 mL water, simmer until creamy, then fold in spinach.'],t:[12,15],e:['saucepan','knife','wooden spoon'],f:['warming','savory','tomato'],x:['creamy','tender'],mp:[true,3,0,'good','airtight container','Add a splash of water and reheat until steaming.'],fs:'Cool promptly and refrigerate cooked oats within 2 hours.',sub:['Use quinoa flakes for oats.','Use chopped green beans for peas.']},
      {n:'Spinach Besan Chilla',s:'Savory chickpea-flour pancakes with spinach, onion, and tomato.',r:'North Indian-inspired',p:['Chickpea flour'],y:'2 medium chillas',i:[I('besan',140,1.25,'cups','Batter'),I('spinach',100,4,'cups','Produce',false,null,'chopped'),I('onion',80,0.5,'cup','Produce'),I('tomato',100,0.55,'cup','Produce'),I('oil',12,2.5,'teaspoons','Pantry'),I('spices',5,2,'teaspoons','Seasoning')],m:['Whisk chickpea flour, spices, and 260 mL water into a pourable batter.','Fold in spinach, onion, and tomato; rest for 5 minutes.','Cook four chillas in a lightly oiled skillet until browned and set on both sides.'],t:[15,18],e:['mixing bowl','whisk','nonstick skillet','spatula'],f:['earthy','spiced'],x:['tender','crisp-edged'],mp:[true,3,30,'good','parchment-lined container','Reheat in a dry skillet.'],fs:'Cook until no wet batter remains; refrigerate within 2 hours.',sub:['Use grated zucchini for spinach.','Use scallion for onion.']},
      {n:'Tomato Paneer Bhurji',s:'Crumbled paneer scrambled with tomato, pepper, onion, and spinach.',r:'North Indian-inspired',p:['Paneer'],y:'1 bowl',i:[I('paneer',240,1.5,'cups','Protein',false,null,'crumbled'),I('tomato',180,1,'cup','Produce'),I('pepper',120,0.85,'cup','Produce'),I('onion',80,0.5,'cup','Produce'),I('spinach',80,3.3,'cups','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('spices',5,2,'teaspoons','Seasoning')],m:['Heat oil and cook onion and pepper until softened.','Add tomato and spices; cook until thick and fragrant.','Fold in crumbled paneer and spinach and cook until hot throughout.'],t:[12,15],e:['large skillet','knife','spatula'],f:['tomato','warming spice'],x:['crumbly','tender'],mp:[true,3,0,'good','airtight container','Reheat gently until steaming.'],fs:'Keep paneer chilled and refrigerate leftovers promptly.',sub:['Use firm tofu for paneer to remove dairy.','Use peas for spinach.']}
    ],
    Lunch:[
      {n:'Chana Masala Rice Bowl',s:'Tomato-spiced chickpeas over brown rice with spinach.',r:'North Indian-inspired',p:['Chickpeas'],y:'1 rice bowl',i:[I('chickpeas',300,1.75,'cups','Protein'),I('rice',260,1.6,'cups','Grain'),I('tomato',220,1.2,'cups','Sauce'),I('onion',100,0.65,'cup','Produce'),I('spinach',100,4,'cups','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('lemon',25,1.7,'tablespoons','Finish'),I('spices',6,2.5,'teaspoons','Seasoning')],m:['Cook onion in oil until golden; add spices and stir for 30 seconds.','Add tomato and chickpeas and simmer until thickened, then fold in spinach.','Divide cooked rice into bowls, spoon over chana masala, and finish with lemon.'],t:[15,25],e:['saucepan','knife','wooden spoon','2 bowls'],f:['tangy','warming','earthy'],x:['saucy','tender'],mp:[true,4,60,'excellent','divided airtight container','Reheat until steaming; add lemon after heating.'],fs:'Cool rice quickly and refrigerate in shallow containers.',sub:['Use white beans for chickpeas.','Use quinoa for brown rice.']},
      {n:'Chicken Tikka Cucumber Salad',s:'Spiced chicken with cucumber, tomato, and yogurt dressing.',r:'Indian restaurant-inspired',p:['Chicken','Greek yogurt'],y:'1 large entree salad',i:[I('chicken',300,10.6,'ounces','Protein',false,null,'raw'),I('yogurt',160,0.67,'cup','Marinade and dressing'),I('cucumber',220,2.1,'cups','Produce'),I('tomato',180,1,'cup','Produce'),I('onion',60,0.4,'cup','Produce'),I('spinach',100,4,'cups','Greens'),I('lemon',30,2,'tablespoons','Dressing'),I('spices',6,2.5,'teaspoons','Seasoning')],m:['Coat chicken with half the yogurt, half the lemon, and the spices; refrigerate for 30 minutes.','Cook chicken in a hot skillet until browned and 74 C / 165 F, then rest and slice.','Toss vegetables with remaining yogurt and lemon and top with the chicken.'],t:[20,15],e:['mixing bowl','large skillet','instant-read thermometer','knife'],f:['tangy','spiced','fresh'],x:['juicy','crisp'],mp:[false,2,0,'best fresh','divided airtight container','Reheat chicken separately; keep salad cold.'],safe:74,fs:'Marinate chicken under refrigeration and discard used marinade.',sub:['Use firm tofu for chicken.','Use dairy-free soy yogurt for Greek yogurt.']},
      {n:'Red Lentil Dal with Rice',s:'A gently spiced lentil dal with tomato, spinach, and rice.',r:'Indian home-style',p:['Lentils'],y:'1 bowl dal with rice',i:[I('lentils',340,1.7,'cups','Protein'),I('rice',240,1.5,'cups','Grain'),I('tomato',180,1,'cup','Sauce'),I('onion',80,0.5,'cup','Produce'),I('spinach',100,4,'cups','Produce'),I('oil',9,2,'teaspoons','Pantry'),I('spices',6,2.5,'teaspoons','Seasoning')],m:['Cook onion in oil, add spices, and stir until fragrant.','Add tomato, cooked lentils, and 300 mL water; simmer for 15 minutes.','Fold in spinach and serve the dal over hot cooked rice.'],t:[12,22],e:['saucepan','knife','wooden spoon'],f:['earthy','warming'],x:['creamy','soft'],mp:[true,4,60,'excellent','shallow airtight container','Reheat with a splash of water until steaming.'],fs:'Cool rice and dal promptly and refrigerate separately when practical.',sub:['Use chickpeas for lentils.','Use quinoa for rice.']}
    ],
    Dinner:[
      {n:'Palak Tofu with Brown Rice',s:'Tofu in a spiced spinach sauce served over brown rice.',r:'Palak paneer-inspired plant-based dish',p:['Tofu'],y:'1 bowl',i:[I('tofu',320,2.5,'cups','Protein',false,null,'pressed and cubed'),I('spinach',300,12,'cups','Sauce'),I('rice',260,1.6,'cups','Grain'),I('tomato',160,0.9,'cup','Sauce'),I('onion',100,0.65,'cup','Produce'),I('oil',12,2.5,'teaspoons','Pantry'),I('spices',6,2.5,'teaspoons','Seasoning')],m:['Brown tofu in half the oil and transfer to a plate.','Cook onion, tomato, and spices in remaining oil; add spinach and cook until wilted.','Blend the spinach mixture carefully, return it to the pan with tofu, simmer, and serve over rice.'],t:[18,25],e:['large skillet','blender','spatula','saucepan'],f:['earthy','warming'],x:['silky','tender'],mp:[true,4,60,'excellent','airtight container','Reheat until steaming, stirring often.'],fs:'Vent hot ingredients when blending and cool leftovers within 2 hours.',sub:['Use paneer for tofu if dairy is acceptable.','Use quinoa for brown rice.']},
      {n:'Home-Style Chicken Curry',s:'Chicken simmered with tomato, onion, spinach, and spices over rice.',r:'Indian home-style',p:['Chicken'],y:'1 curry bowl',i:[I('chicken',340,12,'ounces','Protein',false,null,'raw and cubed'),I('rice',260,1.6,'cups','Grain'),I('tomato',220,1.2,'cups','Sauce'),I('onion',120,0.75,'cup','Produce'),I('spinach',120,5,'cups','Produce'),I('oil',12,2.5,'teaspoons','Pantry'),I('spices',7,3,'teaspoons','Seasoning')],m:['Cook onion in oil until golden, then add spices and tomato.','Add chicken and 250 mL water; cover and simmer until chicken reaches 74 C / 165 F.','Fold in spinach and serve the curry over hot cooked rice.'],t:[18,30],e:['heavy saucepan','instant-read thermometer','knife','wooden spoon'],f:['warming','tomato','savory'],x:['saucy','tender'],mp:[true,4,60,'excellent','shallow airtight container','Reheat to 74 C / 165 F.'],safe:74,fs:'Keep raw chicken separate and verify each piece is fully cooked.',sub:['Use turkey breast for chicken.','Use chickpeas for a plant-based version.']},
      {n:'Coconut Salmon Curry',s:'Salmon and vegetables in a light coconut curry with rice.',r:'Coastal Indian-inspired',p:['Salmon'],y:'1 curry bowl',i:[I('salmon',300,10.6,'ounces','Protein',false,null,'raw and cubed'),I('coconutMilk',240,1,'cup','Sauce'),I('rice',240,1.5,'cups','Grain'),I('tomato',160,0.9,'cup','Sauce'),I('pepper',140,1,'cup','Produce'),I('spinach',100,4,'cups','Produce'),I('lime',25,1.7,'tablespoons','Finish'),I('spices',6,2.5,'teaspoons','Seasoning')],m:['Simmer coconut milk, tomato, pepper, spices, and 120 mL water for 10 minutes.','Add salmon and cook gently until opaque and 63 C / 145 F.','Fold in spinach, finish with lime, and serve over hot rice.'],t:[15,20],e:['wide saucepan','instant-read thermometer','wooden spoon'],f:['coconut','warming','tangy'],x:['silky','flaky'],mp:[true,3,30,'good','airtight container','Reheat gently until steaming.'],safe:63,fs:'Cook fish to 63 C / 145 F under FDA consumer guidance and chill promptly.',sub:['Use shrimp for salmon.','Use tofu for a plant-based curry.'],c:'premium'}
    ],
    Snack:[
      {n:'Cucumber Mint Raita Cups',s:'Cooling cucumber yogurt with mint-style herbs and toasted chickpeas.',r:'Indian accompaniment adapted as a snack',p:['Greek yogurt','Chickpeas'],y:'1 snack cup',i:[I('yogurt',300,1.25,'cups','Protein'),I('cucumber',200,1.9,'cups','Produce',false,null,'grated and squeezed'),I('chickpeas',100,0.6,'cup','Crunch'),I('spices',3,1,'teaspoon','Seasoning'),I('lemon',15,1,'tablespoon','Finish')],m:['Stir yogurt, cucumber, lemon, and seasoning together.','Toast cooked chickpeas in a dry skillet until lightly crisp.','Divide raita into cups and add chickpeas just before serving.'],t:[10,8],e:['mixing bowl','small skillet','2 cups'],f:['cooling','tangy','herbal'],x:['creamy','crisp'],mp:[true,2,0,'excellent','separate topping cup','Serve cold.'],fs:'Keep yogurt refrigerated and do not leave at room temperature longer than 2 hours.',sub:['Use dairy-free soy yogurt.','Use roasted peas for chickpeas.']},
      {n:'Masala Roasted Chickpeas',s:'Crunchy chickpeas with lemon and aromatic spices.',r:'Indian-inspired snack',p:['Chickpeas'],y:'about 3/4 cup',i:[I('chickpeas',300,1.75,'cups','Protein',false,null,'rinsed and dried'),I('oil',9,2,'teaspoons','Pantry'),I('spices',6,2.5,'teaspoons','Seasoning'),I('lemon',20,1.5,'tablespoons','Finish'),I('cucumber',160,1.5,'cups','Produce',true,null,'sliced')],m:['Heat oven to 205 C / 400 F and dry chickpeas thoroughly.','Toss with oil and spices and roast until crisp, shaking the pan twice.','Cool briefly, finish with lemon, and serve with optional cucumber.'],t:[8,32],e:['sheet pan','mixing bowl','clean towel'],f:['warming','tangy'],x:['crisp'],mp:[true,2,0,'good','loosely covered container','Refresh in a hot oven for 5 minutes.'],fs:'Cool completely before covering to prevent trapped steam.',sub:['Use cooked lentils, roasted until crisp.','Use lime for lemon.']},
      {n:'Mango Cardamom Lassi',s:'A thick yogurt and mango drink with cardamom-style spice.',r:'Indian yogurt beverage',p:['Greek yogurt'],y:'1 glass',i:[I('yogurt',300,1.25,'cups','Protein'),I('mango',240,1.5,'cups','Fruit'),I('milk',180,0.75,'cup','Liquid'),I('spices',2,0.5,'teaspoon','Seasoning'),I('almonds',20,2.5,'tablespoons','Finish',true,null,'chopped')],m:['Add yogurt, mango, milk, and spice to a blender.','Blend until completely smooth, adding a splash of cold water if needed.','Pour into two glasses and top with optional chopped almonds.'],t:[8,0],e:['blender','2 glasses'],f:['mango','tangy','aromatic'],x:['thick','smooth'],mp:[false,1,0,'best fresh','sealed bottle','Shake and serve cold.'],fs:'Keep dairy ingredients cold and refrigerate immediately if not serving.',sub:['Use dairy-free soy yogurt and milk.','Use banana for mango.']}
    ]
  });

  addPack('Japanese',{
    Breakfast:[
      {n:'Tamagoyaki Rice Bowl',s:'Soft rolled-style egg over rice with spinach and sesame.',r:'Japanese-inspired breakfast bowl',p:['Egg'],y:'1 rice bowl',i:[I('egg',200,4,'large egg','Protein'),I('whiteRice',260,1.65,'cups','Grain'),I('spinach',120,5,'cups','Produce'),I('soySauce',12,2.5,'teaspoons','Seasoning'),I('sesame',10,1,'tablespoon','Finish'),I('oil',5,1,'teaspoon','Pantry')],m:['Whisk eggs with half the tamari and cook in thin folded layers in an oiled skillet.','Wilt spinach in the same skillet and season with the remaining tamari.','Divide hot rice into bowls, slice the egg, and arrange with spinach and sesame.'],t:[12,12],e:['nonstick skillet','whisk','spatula','2 bowls'],f:['savory','sesame'],x:['soft','fluffy'],mp:[true,2,0,'good','divided airtight container','Reheat rice and spinach; warm egg gently.'],fs:'Cook eggs until set and cool rice promptly.',sub:['Use tofu scramble for egg.','Use brown rice for white rice.']},
      {n:'Miso Tofu Breakfast Soup',s:'Miso broth with tofu, mushrooms, spinach, and rice.',r:'Japanese-inspired breakfast soup',p:['Tofu'],y:'1 soup bowl',i:[I('tofu',240,1.9,'cups','Protein',false,null,'cubed'),I('miso',32,2,'tablespoons','Broth'),I('mushroom',160,2.25,'cups','Produce'),I('spinach',100,4,'cups','Produce'),I('whiteRice',180,1.15,'cups','Grain'),I('seaweed',40,0.5,'cup','Produce'),I('sesame',6,2,'teaspoons','Finish')],m:['Simmer mushrooms and seaweed in 700 mL water until tender.','Add tofu and rice and heat gently without vigorous boiling.','Remove from heat, dissolve miso in a ladle of broth, stir it back in, and finish with sesame.'],t:[12,15],e:['saucepan','ladle','small bowl'],f:['umami','mild'],x:['brothy','soft'],mp:[true,3,0,'good','airtight container','Reheat gently; avoid a hard boil.'],fs:'Cool cooked rice soup quickly and refrigerate within 2 hours.',sub:['Use edamame for tofu.','Use cabbage for spinach.']},
      {n:'Salmon Onigiri Breakfast Plate',s:'Rice triangles filled with cooked salmon and served with cucumber.',r:'Japanese onigiri-inspired',p:['Salmon'],y:'2 small rice triangles',i:[I('whiteRice',300,1.9,'cups','Grain',false,null,'warm and cooked'),I('salmon',160,5.6,'ounces','Filling',false,null,'fully cooked and flaked'),I('cucumber',180,1.7,'cups','Produce'),I('seaweed',8,2,'sheets','Wrap',false,null,'cut into strips'),I('sesame',8,2.5,'teaspoons','Finish'),I('soySauce',8,1.5,'teaspoons','Seasoning')],m:['Mix flaked cooked salmon with tamari.','With damp hands, shape rice around the filling into four compact triangles.','Wrap with seaweed, sprinkle with sesame, and serve with cucumber.'],t:[18,0],e:['mixing bowl','small bowl','knife'],f:['savory','umami'],x:['tender','compact'],mp:[false,1,0,'best fresh','tightly wrapped container','Serve at room temperature or chilled; do not leave out.'],safe:63,fs:'Use fully cooked salmon and cool shaped rice promptly; refrigerate within 2 hours.',sub:['Use drained tuna for salmon.','Use mashed edamame for a fish-free filling.']}
    ],
    Lunch:[
      {n:'Teriyaki Chicken Donburi',s:'Glazed chicken and broccoli over rice.',r:'Japanese donburi-inspired',p:['Chicken'],y:'1 rice bowl',i:[I('chicken',300,10.6,'ounces','Protein',false,null,'raw and sliced'),I('whiteRice',280,1.8,'cups','Grain'),I('broccoli',240,2.5,'cups','Produce'),I('carrot',120,1,'cup','Produce'),I('soySauce',24,5,'teaspoons','Sauce'),I('honey',18,2.5,'teaspoons','Sauce'),I('oil',9,2,'teaspoons','Pantry'),I('sesame',8,2.5,'teaspoons','Finish')],m:['Whisk tamari and honey; reserve half away from the raw chicken.','Stir-fry chicken in oil until 74 C / 165 F, then glaze with the reserved clean sauce.','Steam vegetables and serve with chicken over rice, finished with sesame.'],t:[15,18],e:['large skillet','saucepan','instant-read thermometer','2 bowls'],f:['sweet-savory','umami'],x:['glazed','crisp-tender'],mp:[true,4,30,'excellent','divided airtight container','Reheat to 74 C / 165 F.'],safe:74,fs:'Do not reuse sauce that contacted raw chicken unless boiled safely.',sub:['Use tofu for chicken.','Use brown rice for white rice.']},
      {n:'Soba Tofu Sesame Salad',s:'Chilled soba with tofu, cabbage, cucumber, and sesame-lime dressing.',r:'Japanese-inspired noodle salad',p:['Tofu'],y:'1 noodle salad bowl',i:[I('soba',300,3,'cups','Noodles'),I('tofu',260,2.1,'cups','Protein',false,null,'pressed and cubed'),I('cabbage',180,2,'cups','Produce'),I('cucumber',180,1.7,'cups','Produce'),I('carrot',100,0.85,'cup','Produce'),I('soySauce',20,4,'teaspoons','Dressing'),I('sesame',14,1.5,'tablespoons','Dressing'),I('lime',25,1.7,'tablespoons','Dressing')],m:['Rinse cooked soba under cold water and drain thoroughly.','Whisk tamari, lime, sesame, and 20 mL water into a dressing.','Toss noodles with tofu and vegetables, add dressing, and chill before serving.'],t:[18,8],e:['saucepan','colander','large bowl','whisk'],f:['sesame','tangy','umami'],x:['chewy','crisp'],mp:[true,3,0,'excellent','airtight container','Serve cold.'],fs:'Chill cooked noodles promptly and keep refrigerated.',sub:['Use rice noodles for a wheat-free version.','Use edamame for tofu.']},
      {n:'Tuna Cucumber Rice Bowl',s:'A simple tuna rice bowl with cucumber, edamame, and sesame.',r:'Japanese-inspired pantry bowl',p:['Tuna','Edamame'],y:'1 rice bowl',i:[I('tuna',240,8.5,'ounces','Protein',false,null,'drained'),I('whiteRice',260,1.65,'cups','Grain'),I('cucumber',220,2.1,'cups','Produce'),I('edamame',160,1.25,'cups','Protein'),I('soySauce',18,3.5,'teaspoons','Dressing'),I('lime',20,1.5,'tablespoons','Dressing'),I('sesame',10,1,'tablespoon','Finish')],m:['Whisk tamari and lime into a dressing.','Divide cooked rice into bowls and arrange tuna, cucumber, and edamame over it.','Spoon over the dressing and finish with sesame.'],t:[12,0],e:['2 bowls','small bowl','knife'],f:['clean','umami','tangy'],x:['tender','crisp'],mp:[true,2,0,'good','divided airtight container','Serve cold or warm rice separately.'],fs:'Use shelf-stable tuna before opening, then refrigerate the assembled bowl promptly.',sub:['Use cooked salmon for tuna.','Use chickpeas for a fish-free version.']}
    ],
    Dinner:[
      {n:'Salmon Teriyaki with Broccoli',s:'Teriyaki-glazed salmon with broccoli and brown rice.',r:'Japanese-inspired weeknight dinner',p:['Salmon'],y:'1 salmon rice plate',i:[I('salmon',320,11.3,'ounces','Protein',false,null,'raw'),I('rice',280,1.7,'cups','Grain'),I('broccoli',280,3,'cups','Produce'),I('soySauce',24,5,'teaspoons','Glaze'),I('honey',18,2.5,'teaspoons','Glaze'),I('sesame',10,1,'tablespoon','Finish'),I('lime',20,1.5,'tablespoons','Finish')],m:['Heat oven to 205 C / 400 F and whisk tamari with honey.','Brush salmon with glaze and roast alongside broccoli until fish reaches 63 C / 145 F.','Serve with hot brown rice and finish with sesame and lime.'],t:[12,18],e:['sheet pan','small bowl','instant-read thermometer'],f:['sweet-savory','umami'],x:['flaky','roasted'],mp:[true,3,30,'good','divided airtight container','Reheat gently until steaming.'],safe:63,fs:'Cook fish to 63 C / 145 F under FDA consumer guidance.',sub:['Use trout for salmon.','Use tofu and reduce cooking time.'],c:'premium'},
      {n:'Chicken Yakitori-Style Rice Bowl',s:'Skillet chicken with peppers, onion, rice, and savory glaze.',r:'Yakitori-inspired home adaptation',p:['Chicken'],y:'1 rice bowl',i:[I('chicken',340,12,'ounces','Protein',false,null,'raw and cubed'),I('whiteRice',280,1.8,'cups','Grain'),I('pepper',180,1.25,'cups','Produce'),I('onion',120,0.75,'cup','Produce'),I('soySauce',24,5,'teaspoons','Glaze'),I('honey',14,2,'teaspoons','Glaze'),I('oil',9,2,'teaspoons','Pantry'),I('sesame',8,2.5,'teaspoons','Finish')],m:['Whisk tamari and honey into a glaze.','Cook chicken in oil until nearly done; add pepper and onion and cook until chicken reaches 74 C / 165 F.','Add glaze, toss until glossy, and serve over rice with sesame.'],t:[15,20],e:['large skillet','instant-read thermometer','small bowl','spatula'],f:['savory','sweet','charred'],x:['juicy','crisp-tender'],mp:[true,4,30,'excellent','divided airtight container','Reheat to 74 C / 165 F.'],safe:74,fs:'Verify chicken reaches 74 C / 165 F and avoid cross-contamination.',sub:['Use turkey breast for chicken.','Use tofu for a plant-based bowl.']},
      {n:'Tofu Vegetable Nabe',s:'A light one-pot tofu, mushroom, cabbage, and spinach hot pot.',r:'Japanese nabe-inspired',p:['Tofu'],y:'1 large soup bowl',i:[I('tofu',320,2.5,'cups','Protein',false,null,'cubed'),I('mushroom',240,3.4,'cups','Produce'),I('cabbage',240,2.7,'cups','Produce'),I('spinach',120,5,'cups','Produce'),I('carrot',120,1,'cup','Produce'),I('miso',28,1.75,'tablespoons','Broth'),I('whiteRice',220,1.4,'cups','Grain'),I('sesame',8,2.5,'teaspoons','Finish')],m:['Arrange tofu, mushroom, cabbage, carrot, and 800 mL water in a wide pot.','Cover and simmer until vegetables are tender, then add spinach.','Remove from heat, dissolve miso into the broth, and serve with rice and sesame.'],t:[18,22],e:['wide lidded pot','ladle','small bowl'],f:['umami','mild'],x:['brothy','tender'],mp:[true,3,0,'good','airtight container','Reheat gently without vigorous boiling.'],fs:'Cool soup quickly in shallow containers and refrigerate promptly.',sub:['Use edamame for tofu.','Use broccoli for cabbage.']}
    ],
    Snack:[
      {n:'Sea Salt Edamame',s:'Warm edamame with sesame and citrus.',r:'Japanese izakaya-inspired snack',p:['Edamame'],y:'about 1 cup',i:[I('edamame',300,2.3,'cups','Protein'),I('sesame',10,1,'tablespoon','Finish'),I('lime',20,1.5,'tablespoons','Finish'),I('spices',2,0.5,'teaspoon','Seasoning'),I('cucumber',160,1.5,'cups','Produce',true,null,'sliced')],m:['Steam edamame until hot and tender.','Toss with sesame, lime, and a small amount of seasoning.','Divide into bowls and serve with optional cucumber.'],t:[5,6],e:['steamer or saucepan','mixing bowl'],f:['salty','citrus','sesame'],x:['tender','firm'],mp:[true,3,30,'good','airtight container','Serve cold or reheat until steaming.'],fs:'Refrigerate cooked edamame within 2 hours.',sub:['Use green peas for edamame to remove soy.','Use lemon for lime.']},
      {n:'Wakame Cucumber Sesame Salad',s:'A crisp cucumber and seaweed snack with sesame dressing.',r:'Japanese sunomono-inspired',p:['Sesame'],y:'1 small salad bowl',i:[I('cucumber',300,2.9,'cups','Produce',false,null,'thinly sliced'),I('seaweed',60,0.75,'cup','Produce',false,null,'rehydrated'),I('sesame',16,1.75,'tablespoons','Finish'),I('soySauce',12,2.5,'teaspoons','Dressing'),I('lime',25,1.7,'tablespoons','Dressing'),I('edamame',100,0.75,'cup','Protein')],m:['Squeeze excess water from cucumber and rehydrated wakame.','Whisk tamari and lime, then toss with cucumber, wakame, and edamame.','Chill for 10 minutes and finish with sesame.'],t:[12,0],e:['mixing bowl','whisk','knife'],f:['tangy','umami','sesame'],x:['crisp','slippery'],mp:[true,2,0,'good','airtight container','Serve cold.'],fs:'Keep rehydrated seaweed and cut cucumber refrigerated.',sub:['Use shredded cabbage for wakame.','Use pumpkin seeds for sesame.']},
      {n:'Miso Egg Snack Box',s:'Jammy eggs with cucumber, carrots, and mild miso dip.',r:'Japanese-inspired snack box',p:['Egg'],y:'1 snack box',i:[I('egg',200,4,'large egg','Protein',false,null,'cooked and peeled'),I('cucumber',180,1.7,'cups','Produce'),I('carrot',160,1.3,'cups','Produce'),I('miso',24,1.5,'tablespoons','Dip'),I('yogurt',80,0.33,'cup','Dip'),I('sesame',8,2.5,'teaspoons','Finish')],m:['Cook eggs until the whites and yolks reach the desired safe set, then chill and peel.','Stir miso with yogurt and 15 mL water to make a dip.','Divide eggs and vegetables into boxes and pack the dip separately.'],t:[12,10],e:['saucepan','small bowl','2 snack boxes'],f:['savory','umami'],x:['creamy','crisp'],mp:[true,2,0,'excellent','divided snack box','Serve cold.'],fs:'Chill cooked eggs promptly and keep the snack box refrigerated.',sub:['Use tofu cubes for egg.','Use dairy-free soy yogurt in the dip.']}
    ]
  });

  addPack('Mediterranean',{
    Breakfast:[
      {n:'Fig Walnut Yogurt Oats',s:'Greek yogurt and oats with dried fig, walnuts, and berries.',r:'Mediterranean-inspired breakfast',p:['Greek yogurt','Walnuts'],y:'1 breakfast bowl',i:[I('yogurt',300,1.25,'cups','Protein'),I('oats',90,1,'cup','Base'),I('fig',60,0.5,'cup','Fruit',false,null,'chopped'),I('walnuts',28,0.25,'cup','Finish'),I('berries',120,0.85,'cup','Fruit'),I('milk',120,0.5,'cup','Base'),I('spices',2,0.5,'teaspoon','Seasoning')],m:['Stir oats, milk, yogurt, and spice together in two bowls or jars.','Cover and refrigerate for at least 6 hours.','Top with figs, berries, and walnuts before serving.'],t:[10,0],e:['2 bowls or jars','spoon'],f:['fig','tangy','warm spice'],x:['creamy','crunchy'],mp:[true,4,0,'excellent','sealed jar','Serve cold.'],fs:'Keep yogurt mixture at 4 C / 40 F or colder.',sub:['Use dates for figs.','Use pumpkin seeds for walnuts.']},
      {n:'Spinach Tomato Egg Skillet',s:'Eggs cooked with spinach, tomato, onion, and feta.',r:'Eastern Mediterranean-inspired',p:['Egg','Feta'],y:'1 skillet portion',i:[I('egg',200,4,'large egg','Protein'),I('spinach',160,6.7,'cups','Produce'),I('tomato',200,1.1,'cups','Produce'),I('onion',80,0.5,'cup','Produce'),I('feta',50,0.4,'cup','Finish',false,null,'crumbled'),I('oil',9,2,'teaspoons','Pantry'),I('spices',4,1.5,'teaspoons','Seasoning')],m:['Cook onion and tomato in oil until softened, then wilt in spinach.','Make four wells, crack in eggs, cover, and cook until the eggs are fully set.','Crumble feta over the skillet, season, and divide between plates.'],t:[12,15],e:['lidded skillet','knife','spatula'],f:['savory','tomato','briny'],x:['soft','tender'],mp:[true,2,0,'good','airtight container','Reheat gently until steaming.'],fs:'Cook eggs to a safe set and refrigerate leftovers promptly.',sub:['Use tofu for eggs.','Omit feta or use a dairy-free alternative.']},
      {n:'Chickpea Breakfast Hash',s:'Crisp potatoes, chickpeas, peppers, spinach, and lemon.',r:'Mediterranean-inspired plant-based breakfast',p:['Chickpeas'],y:'1 breakfast bowl',i:[I('chickpeas',260,1.5,'cups','Protein'),I('potato',300,2,'cups','Base',false,null,'cubed'),I('pepper',160,1.1,'cups','Produce'),I('onion',80,0.5,'cup','Produce'),I('spinach',100,4,'cups','Produce'),I('oil',12,2.5,'teaspoons','Pantry'),I('lemon',25,1.7,'tablespoons','Finish'),I('spices',5,2,'teaspoons','Seasoning')],m:['Brown cooked potato in oil in a large skillet.','Add chickpeas, pepper, onion, and spices and cook until the vegetables soften.','Fold in spinach, finish with lemon, and divide into bowls.'],t:[15,18],e:['large skillet','knife','spatula'],f:['lemony','earthy','herbal'],x:['crisp-edged','tender'],mp:[true,4,30,'excellent','airtight container','Reheat in a skillet until steaming.'],fs:'Cool cooked hash promptly and refrigerate within 2 hours.',sub:['Use white beans for chickpeas.','Use sweet potato for white potato.']}
    ],
    Lunch:[
      {n:'Greek Chicken Quinoa Bowl',s:'Lemon-herb chicken with quinoa, cucumber, tomato, and feta.',r:'Greek-inspired grain bowl',p:['Chicken','Feta'],y:'1 grain bowl',i:[I('chicken',300,10.6,'ounces','Protein',false,null,'raw'),I('quinoa',280,1.5,'cups','Grain'),I('cucumber',200,1.9,'cups','Produce'),I('tomato',180,1,'cup','Produce'),I('feta',50,0.4,'cup','Finish'),I('lemon',30,2,'tablespoons','Dressing'),I('oil',12,2.5,'teaspoons','Dressing'),I('spices',5,2,'teaspoons','Seasoning')],m:['Coat chicken with half the oil, lemon, and seasoning; cook until 74 C / 165 F and slice.','Toss quinoa with cucumber, tomato, and the remaining oil and lemon.','Divide into bowls and top with chicken and feta.'],t:[18,18],e:['large skillet','instant-read thermometer','mixing bowl','knife'],f:['lemony','herbal','briny'],x:['tender','crisp'],mp:[true,4,30,'excellent','divided airtight container','Reheat chicken and quinoa; add cold vegetables after heating.'],safe:74,fs:'Keep raw chicken separate and verify safe internal temperature.',sub:['Use chickpeas for chicken.','Omit feta or use dairy-free alternative.']},
      {n:'Lentil Tabbouleh Bowl',s:'Lentils and quinoa with tomato, cucumber, lemon, and herbs.',r:'Levantine tabbouleh-inspired',p:['Lentils'],y:'1 large salad bowl',i:[I('lentils',280,1.4,'cups','Protein'),I('quinoa',240,1.3,'cups','Grain'),I('tomato',220,1.2,'cups','Produce'),I('cucumber',220,2.1,'cups','Produce'),I('spinach',80,3.3,'cups','Greens',false,'Fresh parsley and leafy greens','finely chopped'),I('lemon',40,2.7,'tablespoons','Dressing'),I('oil',18,4,'teaspoons','Dressing'),I('spices',4,1.5,'teaspoons','Seasoning')],m:['Whisk lemon, oil, and seasoning in a large bowl.','Add lentils, quinoa, tomato, cucumber, and finely chopped greens.','Toss well and chill for 15 minutes before serving.'],t:[18,0],e:['large bowl','knife','whisk'],f:['lemony','herbal','fresh'],x:['crisp','tender'],mp:[true,4,0,'excellent','airtight container','Serve cold.'],fs:'Cool cooked quinoa before mixing and refrigerate promptly.',sub:['Use bulgur for quinoa if gluten is acceptable.','Use chickpeas for lentils.']},
      {n:'Tuna White Bean-Style Salad',s:'Tuna and chickpeas with tomato, cucumber, olives, and lemon.',r:'Coastal Mediterranean-inspired',p:['Tuna','Chickpeas'],y:'1 large entree salad',i:[I('tuna',220,7.8,'ounces','Protein',false,null,'drained'),I('chickpeas',240,1.4,'cups','Protein'),I('tomato',180,1,'cup','Produce'),I('cucumber',180,1.7,'cups','Produce'),I('olive',50,0.33,'cup','Finish',false,null,'sliced'),I('spinach',100,4,'cups','Greens'),I('lemon',30,2,'tablespoons','Dressing'),I('oil',12,2.5,'teaspoons','Dressing')],m:['Whisk lemon and oil in a large bowl.','Add tuna, chickpeas, tomato, cucumber, olives, and greens.','Toss gently, divide between plates, and serve chilled.'],t:[15,0],e:['large bowl','knife','whisk'],f:['briny','lemony'],x:['tender','crisp'],mp:[true,2,0,'good','airtight container','Serve cold.'],fs:'Refrigerate opened tuna and the assembled salad promptly.',sub:['Use cooked salmon for tuna.','Use extra chickpeas for a fish-free version.']}
    ],
    Dinner:[
      {n:'Lemon Oregano Chicken Tray',s:'Roasted chicken, potato, tomato, and green beans with lemon herbs.',r:'Greek-inspired sheet-pan dinner',p:['Chicken'],y:'1 chicken and vegetable plate',i:[I('chicken',340,12,'ounces','Protein',false,null,'raw'),I('potato',320,2,'cups','Produce',false,null,'cubed'),I('greenBeans',240,2.1,'cups','Produce'),I('tomato',200,1.1,'cups','Produce'),I('lemon',40,2.7,'tablespoons','Finish'),I('oil',18,4,'teaspoons','Pantry'),I('spices',6,2.5,'teaspoons','Seasoning')],m:['Heat oven to 220 C / 425 F and line a sheet pan.','Toss potato and green beans with oil and seasoning; add chicken and tomato.','Roast until chicken reaches 74 C / 165 F and vegetables are tender, then finish with lemon.'],t:[15,32],e:['sheet pan','mixing bowl','instant-read thermometer'],f:['lemony','oregano-like','savory'],x:['roasted','juicy'],mp:[true,4,60,'excellent','shallow airtight container','Reheat to 74 C / 165 F.'],safe:74,fs:'Avoid raw chicken cross-contamination and verify safe internal temperature.',sub:['Use turkey tenderloin for chicken.','Use zucchini for green beans.']},
      {n:'Herbed Salmon Couscous Plate',s:'Roasted salmon with whole-wheat couscous and chopped vegetables.',r:'Mediterranean coastal-inspired',p:['Salmon'],y:'1 salmon grain plate',i:[I('salmon',320,11.3,'ounces','Protein',false,null,'raw'),I('couscous',280,2,'cups','Grain'),I('tomato',180,1,'cup','Produce'),I('cucumber',180,1.7,'cups','Produce'),I('spinach',100,4,'cups','Greens'),I('lemon',30,2,'tablespoons','Dressing'),I('oil',12,2.5,'teaspoons','Dressing'),I('spices',5,2,'teaspoons','Seasoning')],m:['Heat oven to 205 C / 400 F; season salmon and roast until 63 C / 145 F.','Toss cooked couscous with tomato, cucumber, greens, lemon, and oil.','Divide couscous between plates and top with salmon.'],t:[15,18],e:['sheet pan','mixing bowl','instant-read thermometer'],f:['lemony','herbal'],x:['flaky','tender'],mp:[true,3,30,'good','divided airtight container','Reheat salmon and couscous gently; keep cucumber cold.'],safe:63,fs:'Cook fish to 63 C / 145 F under FDA consumer guidance.',sub:['Use quinoa for a gluten-free version.','Use trout for salmon.'],c:'premium'},
      {n:'Lentil Feta Stuffed Peppers',s:'Roasted peppers filled with lentils, quinoa, tomato, spinach, and feta.',r:'Mediterranean-inspired vegetarian dinner',p:['Lentils','Feta'],y:'2 pepper halves',i:[I('pepper',300,2,'large peppers','Shell',false,null,'halved'),I('lentils',300,1.5,'cups','Protein'),I('quinoa',220,1.2,'cups','Grain'),I('tomato',180,1,'cup','Produce'),I('spinach',100,4,'cups','Produce'),I('feta',60,0.5,'cup','Finish'),I('oil',9,2,'teaspoons','Pantry'),I('spices',5,2,'teaspoons','Seasoning')],m:['Heat oven to 190 C / 375 F and arrange pepper halves in a baking dish.','Mix lentils, quinoa, tomato, spinach, oil, seasoning, and half the feta; fill the peppers.','Cover and bake until tender, uncover, add remaining feta, and bake 5 minutes more.'],t:[20,35],e:['baking dish','mixing bowl','knife'],f:['savory','tomato','briny'],x:['tender','hearty'],mp:[true,4,60,'excellent','airtight container','Reheat until steaming throughout.'],fs:'Cool baked peppers promptly and refrigerate within 2 hours.',sub:['Omit feta for a vegan version.','Use chickpeas for lentils.']}
    ],
    Snack:[
      {n:'Hummus Vegetable Snack Box',s:'Chickpea tahini dip with cucumber, carrot, and pepper.',r:'Levantine hummus-inspired snack',p:['Chickpeas','Tahini'],y:'1 snack box',i:[I('chickpeas',260,1.5,'cups','Dip'),I('tahini',32,2,'tablespoons','Dip'),I('lemon',30,2,'tablespoons','Dip'),I('oil',9,2,'teaspoons','Dip'),I('cucumber',180,1.7,'cups','Produce'),I('carrot',160,1.3,'cups','Produce'),I('pepper',160,1.1,'cups','Produce'),I('spices',3,1,'teaspoon','Seasoning')],m:['Blend chickpeas, tahini, lemon, oil, seasoning, and 60 mL water until smooth.','Cut cucumber, carrot, and pepper into dipping pieces.','Divide hummus and vegetables between two snack boxes.'],t:[15,0],e:['food processor','knife','2 snack boxes'],f:['lemony','sesame','earthy'],x:['creamy','crisp'],mp:[true,4,0,'excellent','divided airtight container','Serve cold.'],fs:'Refrigerate homemade hummus promptly and use clean utensils.',sub:['Use sunflower seed butter for tahini to remove sesame.','Use white beans for chickpeas.']},
      {n:'Honey Walnut Yogurt Cups',s:'Greek yogurt with walnuts, honey, and warm spice.',r:'Eastern Mediterranean-inspired',p:['Greek yogurt','Walnuts'],y:'1 snack cup',i:[I('yogurt',320,1.33,'cups','Protein'),I('walnuts',30,0.27,'cup','Finish'),I('honey',20,1,'tablespoon','Finish'),I('fig',50,0.4,'cup','Fruit'),I('spices',2,0.5,'teaspoon','Seasoning')],m:['Divide yogurt between two cups.','Top with chopped figs and walnuts.','Drizzle with honey, add spice, and serve cold.'],t:[7,0],e:['2 cups','knife','spoon'],f:['honey','fig','tangy'],x:['creamy','crunchy'],mp:[true,3,0,'excellent','sealed cup','Serve cold.'],fs:'Keep yogurt refrigerated at 4 C / 40 F or colder.',sub:['Use maple-style syrup for honey.','Use pumpkin seeds for walnuts.']},
      {n:'Tomato Feta Olive Skewers',s:'Bite-size tomato, cucumber, feta, and olive skewers.',r:'Greek salad-inspired snack',p:['Feta'],y:'4 small skewers',i:[I('tomato',200,1.1,'cups','Produce',false,null,'bite-size'),I('cucumber',180,1.7,'cups','Produce',false,null,'cubed'),I('feta',100,0.8,'cup','Protein',false,null,'cubed'),I('olive',50,0.33,'cup','Finish'),I('lemon',20,1.5,'tablespoons','Dressing'),I('oil',9,2,'teaspoons','Dressing'),I('spices',3,1,'teaspoon','Seasoning')],m:['Thread tomato, cucumber, feta, and olives onto eight short skewers.','Whisk lemon, oil, and seasoning.','Drizzle over the skewers immediately before serving.'],t:[15,0],e:['8 short skewers','small bowl','knife'],f:['briny','lemony','fresh'],x:['crisp','creamy'],mp:[true,2,0,'good','airtight container','Serve cold.'],fs:'Keep feta and assembled skewers refrigerated; supervise children with skewers.',sub:['Use firm tofu for feta.','Use bell pepper for olives.']}
    ]
  });

  var recipes=[];
  Object.keys(DATA).forEach(function(cuisine){
    ['Breakfast','Lunch','Dinner','Snack'].forEach(function(slot){
      DATA[cuisine][slot].forEach(function(spec){recipes.push(make(cuisine,slot,spec));});
    });
  });
  window.INSYNC_PILOT_RECIPES=recipes;
  window.INSYNC_PILOT_META={schema:1,collection:'pilot-review',recipeCount:recipes.length,cuisines:Object.keys(DATA),recipesPerCuisine:12,recipesPerCuisineSlot:3,status:'review-only',productionApproved:false,nutritionSource:NUTRIENTS?'USDA FoodData Central specific record mappings with explicit unresolved blockers':'legacy embedded reference fallback',nutrientRegistryVersion:NUTRIENTS&&NUTRIENTS.version||null};
})();
