const API='https://api.github.com';
const enc=new TextEncoder(), dec=new TextDecoder();

function headers(token){return {'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'};}
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s);}
function base64ToBytes(s){const raw=atob(s.replace(/\n/g,''));return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function jsonToBase64(obj){return bytesToBase64(enc.encode(JSON.stringify(obj,null,2)));}
function base64ToJson(s){return JSON.parse(dec.decode(base64ToBytes(s)));}
function normalize(config){return {owner:(config.owner||'').trim(),repo:(config.repo||'').trim(),branch:(config.branch||'main').trim(),token:(config.token||'').trim()};}
function check(config){const c=normalize(config);if(!c.owner||!c.repo||!c.token)throw new Error('Enter the GitHub owner, repository, and token.');return c;}
async function request(path,config,options={}){const c=check(config);const r=await fetch(`${API}${path}`,{...options,headers:{...headers(c.token),...(options.headers||{})}});let data=null;try{data=await r.json();}catch{}if(!r.ok)throw new Error(data?.message||`GitHub returned ${r.status}`);return data;}
export async function testGitHub(config){const c=check(config);const repo=await request(`/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}`,c);return {name:repo.full_name,private:repo.private,defaultBranch:repo.default_branch};}
async function getFile(path,config){const c=check(config);const q=new URLSearchParams({ref:c.branch});const r=await fetch(`${API}/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${path}?${q}`,{headers:headers(c.token)});if(r.status===404)return null;let data=null;try{data=await r.json();}catch{}if(!r.ok)throw new Error(data?.message||`GitHub returned ${r.status}`);return data;}
async function putFile(path,value,config,message){const c=check(config), current=await getFile(path,c);const body={message,content:jsonToBase64(value),branch:c.branch};if(current?.sha)body.sha=current.sha;return request(`/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${path}`,c,{method:'PUT',body:JSON.stringify(body)});}
async function deriveKey(password,salt,usage){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,usage);}
async function encryptJson(value,password){if(!password)throw new Error('Log in again before cloud sync.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(password,salt,['encrypt']);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(value)));return {format:'insync-aes-gcm-v1',salt:bytesToBase64(salt),iv:bytesToBase64(iv),data:bytesToBase64(new Uint8Array(cipher)),updatedAt:new Date().toISOString()};}
async function decryptJson(payload,password){if(!payload?.data)return null;const salt=base64ToBytes(payload.salt),iv=base64ToBytes(payload.iv),key=await deriveKey(password,salt,['decrypt']);try{return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},key,base64ToBytes(payload.data))));}catch{throw new Error('Cloud data could not be unlocked with this profile password.');}}
export async function pushProfile(profile,password,config){const payload=await encryptJson(profile,password);await putFile(`cloud-data/profiles/${profile.id}/profile.enc.json`,payload,config,`InSync: sync ${profile.name} profile`);return payload.updatedAt;}
export async function pullProfile(profileId,password,config){const file=await getFile(`cloud-data/profiles/${profileId}/profile.enc.json`,config);if(!file)return null;return decryptJson(base64ToJson(file.content),password);}
export async function pushShared(shared,config){const value={...shared,updatedAt:new Date().toISOString()};await putFile('cloud-data/shared/shared.json',value,config,'InSync: sync shared accountability');return value.updatedAt;}
export async function pullShared(config){const file=await getFile('cloud-data/shared/shared.json',config);return file?base64ToJson(file.content):null;}
